<?php
define("TTL","APP GESVENTA");
define("LANGS",[
        "es"=>["lang"=>"ESPAÑOL",
                "welcome"=>"BIENVENIDO",
                "user"=>"Nombre",
                "pass"=>"Contraseña",
                "idioma"=>"Idioma",
                "send"=>"Enviar",
                "login"=>"LOGIN",
                "register"=>"REGISTRARSE",
                "logout"=>"SALIR",
                "index"=>"INICIO",
                "cart"=>"CARRITO",
                "Login"=>"LOGIN",
                "Salir"=>"SALIR",
                "Inicio"=>"INICIO",
                "Cart"=>"CARRITO",
                "tituloLogin"=>"Formulario de login",
                "consultar"=>"CONSULTAR",
                "nuevo"=>"NUEVO",
                "borrar"=>"BORRAR",
                "modificar"=>"MODIFICAR",
                "cod"=>"Codigo",
                "nom_prod"=>"Nombre",
                "pvp"=>"Precio",
                "prov"=>"Proovedor",
                "existencias"=>"Existencias",
                "btFiltros"=>"FILTROS",
                "btNuevo" =>"INSERTAR",
                "añadir" =>"AÑADIR",
                "btBorrar"=>"BORRAR",
                "btModificar"=>"MODIFICAR"

        ],
        "en"=>["lang"=>"ENGLISH",
                "welcome"=>"WELCOME",
                "user"=>"Username",
                "pass"=>"Password",
                "idioma"=>"Language",
                "send"=>"Send",
                "login"=>"LOGIN",
                "register"=>"REGISTER",
                "logout"=>"LOGOUT",
                "index"=>"HOME",
                "cart"=>"CARRITO",
                "Login"=>"LOGIN",
                "Salir"=>"EXIT",
                "Inicio"=>"INDEX",
                "Cart"=>"CART",
                "tituloLogin"=>"Login Form",
                "consultar"=>"QUERY",
                "nuevo"=>"NEW",
                "borrar"=>"DELETE",
                "modificar"=>"UPDATE",
                "cod"=>"Code",
                "nom_prod"=>"Name",
                "pvp"=>"Price",
                "prov"=>"Supplier",
                "existencias"=>"Stock",
                "btFiltros"=>"QUERY",
                "btNuevo" =>"INSERT",
                "añadir" =>"ADD",
                "btBorrar"=>"DELETE",
                "btModificar"=>"UPDATE"
        ],
        "fr"=>["lang"=>"FRANÇAIS",
                "welcome"=>"BIENVENU",
                "user"=>"Nom",
                "pass"=>"Mot de Passe",
                "idioma"=>"Langage",
                "send"=>"Envoyer",
                "login"=>"COMMENCER",
                "register"=>"INSCRIRE",
                "logout"=>"SORTIR",
                "index"=>"INIT",
                "cart"=>"CADDIE",
                "Login"=>"LOGIN",
                "Salir"=>"SORTIR",
                "Inicio"=>"COMMENCER",
                "Cart"=>"CADDIE",
                "tituloLogin"=>"Formulario d'entre",
                "consultar"=>"ENVOYER",
                "nuevo"=>"NOUVEAU",
                "borrar"=>"EFFACER",
                "modificar"=>"MODIFIER",
                "cod"=>"Code",
                "nom_prod"=>"Name",
                "pvp"=>"Prix",
                "prov"=>"Fournisseur",
                "existencias"=>"Stock",
                "btFiltros"=>"ENVOYER",
                "btNuevo" =>"INSÉRER",
                "añadir" =>"AJOUTER",
                "btBorrar"=>"EFFACER",
                "btModificar"=>"MODIFIER"

        ],
        "de"=>["lang"=>"DEUTSCH",
                "welcome"=>"WILLKOMMEN",
                "user"=>"Name",
                "pass"=>"Passwort",
                "idioma"=>"Idiom",
                "send"=>"Senden",
                "login"=>"START",
                "register"=>"CHECK-IN",
                "logout"=>"AUSGANG",
                "index"=>"INIT",
                "cart"=>"CADDIE",
                "Login"=>"LOGIN",
                "Salir"=>"EXIT",
                "Inicio"=>"ANFANG",
                "Cart"=>"CART",
                "tituloLogin"=>"Eingabeformular",
                "consultar"=>"ANFRAGE",
                "nuevo"=>"NEU",
                "borrar"=>"LÖSCHEN",
                "modificar"=>"ÄNDERN",
                "cod"=>"Code",
                "nom_prod"=>"Name",
                "pvp"=>"Preis",
                "prov"=>"Anbieter",
                "existencias"=>"Aktie",
                "btFiltros"=>"ANFRAGE",
                "btNuevo" =>"EINFÜGUNG",
                "añadir" =>"HINZUFÜGEN",
                "btBorrar"=>"LÖSCHEN",
                "btModificar"=>"ÄNDERN"
        ],
        "ch"=>[
                "lang"=>"中文",
                "welcome"=>"歡迎",
                "user"=>"用戶名",
                "pass"=>"密碼",
                "idioma"=>"語言",
                "send"=>"發送",
                "login"=>"登錄",
                "register"=>"註冊",
                "logout"=>"退出",
                "index"=>"首頁",
                "cart"=>"購物車",
                "Login"=>"登錄",
                "Salir"=>"退出",
                "Inicio"=>"首頁",
                "Cart"=>"購物車",
                "tituloLogin"=>"登錄表單",
                "consultar"=>"查詢",
                "nuevo"=>"新增",
                "borrar"=>"刪除",
                "modificar"=>"修改",
                "cod"=>"代碼",
                "nom_prod"=>"名稱",
                "pvp"=>"價格",
                "prov"=>"供應商",
                "existencias"=>"庫存",
                "btFiltros"=>"過濾器",
                "btNuevo" =>"插入",
                "añadir" =>"加入",
                "btBorrar"=>"刪除",
                "btModificar"=>"修改"
        ]
]);
define("OPS",[
        // "Login"=>"login.php",
        "Inicio"=>"front_app.php",
        "Salir"=>"login_app.php",
        "Cart"=>"cart_app.php"

]);
define('CRUD', [
        "user"=>["consultar"],
        "admin"=>["consultar", "nuevo", "borrar", "modificar"]
]);
define('NOM',[     
        "cod",
        "nom_prod",
        "pvp",
        "prov",
        "existencias"
]);
define("BOTN",[
        "consultar"=>"btFiltros",
        "nuevo"=>"btNuevo",
        "borrar"=>"btBorrar",
        "modificar"=>"btModificar"
])
?>