<?php
define("TTL","APP GESVENTA");
define("LANGS",[
        "es"=>["lang"=>"ESPAÑOL",
                "welcome"=>"BIENVENIDO",
                "user"=>"Nombre",
                "pass"=>"Contraseña",
                "idioma"=>"Idioma",
                "send"=>"Enviar",
                "login"=>"LOGIN",
                "register"=>"REGISTRARSE",
                "logout"=>"SALIR",
                "index"=>"INICIO",
                "cart"=>"CARRITO",
                "Login"=>"LOGIN",
                "Salir"=>"SALIR",
                "Inicio"=>"INICIO",
                "Cart"=>"CARRITO",
                "tituloLogin"=>"Formulario de login",
                "enviar"=>"CONSULTAR",
                "nuevo"=>"NUEVO",
                "borrar"=>"BORRAR",
                "modificar"=>"MODIFICAR",
                "codigo"=>"codigo",
                "producto"=>"producto",
                "proovedor"=>"proovedor",
                

        ],
        "en"=>["lang"=>"ENGLISH",
                "welcome"=>"WELCOME",
                "user"=>"Username",
                "pass"=>"Password",
                "idioma"=>"Language",
                "send"=>"Send",
                "login"=>"LOGIN",
                "register"=>"REGISTER",
                "logout"=>"LOGOUT",
                "index"=>"HOME",
                "cart"=>"CARRITO",
                "Login"=>"LOGIN",
                "Salir"=>"EXIT",
                "Inicio"=>"INDEX",
                "Cart"=>"CART",
                "tituloLogin"=>"Login Form",
                "enviar"=>"QUERY",
                "nuevo"=>"NEW",
                "borrar"=>"DELETE",
                "modificar"=>"UPDATE"
        ],
        "fr"=>["lang"=>"FRANÇAIS",
                "welcome"=>"BIENVENU",
                "user"=>"Nom",
                "pass"=>"Mot de Passe",
                "idioma"=>"Langage",
                "send"=>"Envoyer",
                "login"=>"COMMENCER",
                "register"=>"INSCRIRE",
                "logout"=>"SORTIR",
                "index"=>"INIT",
                "cart"=>"CADDIE",
                "Login"=>"LOGIN",
                "Salir"=>"SORTIR",
                "Inicio"=>"COMMENCER",
                "Cart"=>"CADDIE",
                "tituloLogin"=>"Formulario d'entre",
                "enviar"=>"ENVOYER",
                "nuevo"=>"NOUVEAU",
                "borrar"=>"EFFACER",
                "modificar"=>"MODIFIER"
        ],
        "de"=>["lang"=>"DEUTSCH",
                "welcome"=>"WILLKOMMEN",
                "user"=>"Name",
                "pass"=>"Passwort",
                "idioma"=>"Idiom",
                "send"=>"Senden",
                "login"=>"START",
                "register"=>"CHECK-IN",
                "logout"=>"AUSGANG",
                "index"=>"INIT",
                "cart"=>"CADDIE",
                "Login"=>"LOGIN",
                "Salir"=>"EXIT",
                "Inicio"=>"ANFANG",
                "Cart"=>"CART",
                "tituloLogin"=>"Eingabeformular",
                "enviar"=>"ANFRAGE",
                "nuevo"=>"NEU",
                "borrar"=>"LÖSCHEN",
                "modificar"=>"ÄNDERN"
        ]
]);
define("OPS",[
        // "Login"=>"login.php",
        "Inicio"=>"front_app.php",
        "Salir"=>"login_app.php",
        "Cart"=>"cart_app.php"

        ]);
define('CRUD', [
        "user"=>["enviar"],
        "admin"=>["enviar", "nuevo", "borrar", "modificar"]
]);
?>